# -*- coding: utf-8 -*-
"""app_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RL0LaZdsqk8_VWROB5FPfZKm1vbrExz7
"""

import gradio as gr
import numpy as np
import pickle

with open("churn_rf_healthym.pkl", "rb") as f:
    model = pickle.load(f)

# Define the prediction function
def predict(age, income_level, education, device_type, tech_comfort_score, total_sessions, gross_session_length, active_days):
    # Define categories in the same order as used during training
    income_categories = ["Low", "Medium", "High", "Very High"]
    education_categories = ["High School", "Other", "Graduate", "Post Graduate"]
    device_type_categories = ["Multi-device", "Mobile-only", "Desktop-only"]

    # One-hot encode with drop='first' logic
    income_encoded = [1 if income_level == cat else 0 for cat in income_categories[1:]]
    education_encoded = [1 if education == cat else 0 for cat in education_categories[1:]]
    device_type_encoded = [1 if device_type == cat else 0 for cat in device_type_categories[1:]]

    # Combine features: [income_encoded, education_encoded, age]
    input_data = np.array([income_encoded + education_encoded + device_type_encoded + [age] + [tech_comfort_score] + [total_sessions] + [gross_session_length] + [active_days]])

    # Predict probability of class 1 (e.g., renewal)
    probability = model.predict_proba(input_data)[0][1]
    return f"Renewal Probability: {probability:.2f}"

# Create the Gradio interface
iface = gr.Interface(
    fn=predict,
    inputs=[
        gr.Number(label="Age"),
        gr.Number(label="Active Days"),
        gr.Number(label = "Total Sessions"),
        gr.Number(label = "Gross Session Length"),
        gr.Dropdown(["low", "medium", "high", "very high"], label="Income Range"),
        gr.Radio(["high school",  "other", "graduate", "post graduate"], label="Education"),
        gr.Dropdown(["multi-device",  "mobile-only", "desktop-only"], label="Device type"),
        gr.Slider(minimum= 0, maximum= 5, step= 1, label="Tech Comfort Score")


    ],
    outputs="text",
    title="Customer Renewal Probability Predictor",
    description= "Predict a customer's likelihood of renewing their subscription.",
    theme = gr.themes.Soft()
)

# Launch the app
iface.launch()