# -*- coding: utf-8 -*-
"""app_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RL0LaZdsqk8_VWROB5FPfZKm1vbrExz7
"""

import streamlit as st
import numpy as np
import pickle

with open("churn_rf_healthym.pkl", "rb") as f:
    model = pickle.load(f)

# Define the prediction function
def predict(age, income_level, education, device_type, tech_comfort_score, total_sessions, gross_session_length, active_days):
    # Define categories in the same order as used during training
    income_categories = ["Low", "Medium", "High", "Very High"]
    education_categories = ["High School", "Other", "Graduate", "Post Graduate"]
    device_type_categories = ["Multi-device", "Mobile-only", "Desktop-only"]

    # One-hot encode with drop='first' logic
    income_encoded = [1 if income_level == cat else 0 for cat in income_categories[1:]]
    education_encoded = [1 if education == cat else 0 for cat in education_categories[1:]]
    device_type_encoded = [1 if device_type == cat else 0 for cat in device_type_categories[1:]]

    # Combine features: [income_encoded, education_encoded, age]
    input_data = np.array([income_encoded + education_encoded + device_type_encoded + [age] + [tech_comfort_score] + [total_sessions] + [gross_session_length] + [active_days]])

    # Predict probability of class 1 (e.g., renewal)
    probability = model.predict_proba(input_data)[0][1]
    return probability # Return the raw probability

# Create the Gradio interface

st.title("📈 Customer Renewal Probability Predictor")

with st.container():

  st.subheader("Enter customer information below.")

col1, col2 = st.columns(2)
with col1:
  age = st.number_input("Age", step =1)
  active_days = st.number_input("Active Days", step =1)
  total_sessions = st.number_input("Total Sessions", step=1)
  gross_length = st.number_input("Gross Session Length", step=1)

with col2:
  income = st.selectbox("Income Range", ["low", "medium", "high", "very high"])
  education = st.radio("Education", ["high school",  "other", "graduate", "post graduate"])
  device = st.selectbox("Device Type", ["multi-device",  "mobile-only", "desktop-only"])
  tech_score= st.slider("Tech Comfort Score", min_value= 0, max_value= 5, step= 1)


if st.button("Predict Renewal Probability"):

    prediction = predict(
        age,
        income,
        education,
        device,
        tech_score,
        total_sessions,
        gross_length,
        active_days
    )
    with st.container():

     st.metric("Renewal Probability", f"{prediction:.1%}")

    # 7. Color-code the risk level
     if prediction >= 0.75:
        st.success("🟢 Low Risk")

     elif prediction >= 0.50:
         st.warning("🟡 Medium Risk")

     else:
        st.error("🔴 High Risk")

    # 8. Show a progress bar
    st.progress(prediction)